// user login action types
export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';


//user signup action types
export const USER_SIGNUP = 'USER_SIGNUP';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

//Events action types
export const EVENT_CREATED_SUCCESS = 'EVENT_CREATED_SUCCESS';
export const EVENT_CREATED_FAILED = 'EVENT_CREATED_FAILED';

export const EVENTS_FETCHED = 'EVENTS_FETCHED';
export const EVENTS_FETCHED_FAILED = 'EVENTS_FETCHED_FAILED';

export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILED = 'EDIT_EVENT_FAILED';

export const EVENT_DELETED_SUCCESS = 'EVENT_DELETED_SUCCESS';
export const EVENT_DELETED_FAILED = 'EVENT_DELETED_FAILED';

export const MY_EVENTS_FETCHED = 'MY_EVENTS_FETCHED';
export const MY_EVENTS_FETCHED_FAILED = 'MY_EVENTS_FETCHED_FAILED';

export const EVENT_DELETED = 'EVENT_DELETED';



//set Authentication
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';
export const SET_AUTH_FAILED = 'SET_AUTH_FAILED';
